/* graph.c generated by valac 0.24.0, the Vala compiler
 * generated from graph.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <cairo.h>


#define GNODE_TYPE_GRAPH (gnode_graph_get_type ())
#define GNODE_GRAPH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNODE_TYPE_GRAPH, GNodeGraph))
#define GNODE_GRAPH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNODE_TYPE_GRAPH, GNodeGraphClass))
#define GNODE_IS_GRAPH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNODE_TYPE_GRAPH))
#define GNODE_IS_GRAPH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNODE_TYPE_GRAPH))
#define GNODE_GRAPH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNODE_TYPE_GRAPH, GNodeGraphClass))

typedef struct _GNodeGraph GNodeGraph;
typedef struct _GNodeGraphClass GNodeGraphClass;
typedef struct _GNodeGraphPrivate GNodeGraphPrivate;

#define GNODE_TYPE_NODE (gnode_node_get_type ())
#define GNODE_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNODE_TYPE_NODE, GNodeNode))
#define GNODE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNODE_TYPE_NODE, GNodeNodeClass))
#define GNODE_IS_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNODE_TYPE_NODE))
#define GNODE_IS_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNODE_TYPE_NODE))
#define GNODE_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNODE_TYPE_NODE, GNodeNodeClass))

typedef struct _GNodeNode GNodeNode;
typedef struct _GNodeNodeClass GNodeNodeClass;

#define GNODE_TYPE_LINK (gnode_link_get_type ())
#define GNODE_LINK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNODE_TYPE_LINK, GNodeLink))
#define GNODE_LINK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNODE_TYPE_LINK, GNodeLinkClass))
#define GNODE_IS_LINK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNODE_TYPE_LINK))
#define GNODE_IS_LINK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNODE_TYPE_LINK))
#define GNODE_LINK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNODE_TYPE_LINK, GNodeLinkClass))

typedef struct _GNodeLink GNodeLink;
typedef struct _GNodeLinkClass GNodeLinkClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GNodeGraph {
	GObject parent_instance;
	GNodeGraphPrivate * priv;
};

struct _GNodeGraphClass {
	GObjectClass parent_class;
};

struct _GNodeGraphPrivate {
	gchar* _title;
	GeeArrayList* _nodes;
	GeeArrayList* _edges;
};


static gpointer gnode_graph_parent_class = NULL;

GType gnode_graph_get_type (void) G_GNUC_CONST;
GType gnode_node_get_type (void) G_GNUC_CONST;
GType gnode_link_get_type (void) G_GNUC_CONST;
#define GNODE_GRAPH_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GNODE_TYPE_GRAPH, GNodeGraphPrivate))
enum  {
	GNODE_GRAPH_DUMMY_PROPERTY,
	GNODE_GRAPH_TITLE
};
GNodeGraph* gnode_graph_new (const gchar* title);
GNodeGraph* gnode_graph_construct (GType object_type, const gchar* title);
static void gnode_graph_set_title (GNodeGraph* self, const gchar* value);
static void gnode_graph_set_nodes (GNodeGraph* self, GeeArrayList* value);
static void gnode_graph_set_edges (GNodeGraph* self, GeeArrayList* value);
gboolean gnode_graph_is_connected (GNodeGraph* self);
static GeeArrayList* gnode_graph_get_nodes (GNodeGraph* self);
static gboolean gnode_graph_traverse_nodes (GNodeGraph* self, GNodeNode* first, GeeArrayList* visited);
void gnode_graph_add_node (GNodeGraph* self, GNodeNode* node);
void gnode_graph_self_loop (GNodeGraph* self, GNodeNode* node, GNodeLink* edge);
void gnode_graph_remove_link (GNodeGraph* self, GNodeLink* edge);
static GeeArrayList* gnode_graph_get_edges (GNodeGraph* self);
GeeArrayList* gnode_graph_shortest_path (GNodeGraph* self, GNodeNode* src, GNodeNode* dst);
void gnode_graph_remove_edge (GNodeGraph* self, GNodeLink* edge);
void gnode_graph_add_edge (GNodeGraph* self, GNodeLink* edge);
void gnode_graph_draw (GNodeGraph* self, cairo_t* ctx);
void gnode_link_draw (GNodeLink* self, cairo_t* ctx);
void gnode_graph_remove_node (GNodeGraph* self, GNodeNode* node);
GeeArrayList* gnode_node_get_edges (GNodeNode* self);
GNodeNode* gnode_link_get_pair (GNodeLink* self, GNodeNode* node);
void gnode_node_unlink (GNodeNode* self, GNodeLink* edge);
const gchar* gnode_graph_get_title (GNodeGraph* self);
static void gnode_graph_finalize (GObject* obj);
static void _vala_gnode_graph_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gnode_graph_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GNodeGraph* gnode_graph_construct (GType object_type, const gchar* title) {
	GNodeGraph * self = NULL;
	const gchar* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	GeeArrayList* _tmp2_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
	GeeArrayList* _tmp4_ = NULL;
	self = (GNodeGraph*) g_object_new (object_type, NULL);
	_tmp0_ = title;
	if (_tmp0_ == NULL) {
		gnode_graph_set_title (self, "");
	}
	_tmp1_ = gee_array_list_new (GNODE_TYPE_NODE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_tmp2_ = _tmp1_;
	gnode_graph_set_nodes (self, _tmp2_);
	_g_object_unref0 (_tmp2_);
	_tmp3_ = gee_array_list_new (GNODE_TYPE_LINK, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_tmp4_ = _tmp3_;
	gnode_graph_set_edges (self, _tmp4_);
	_g_object_unref0 (_tmp4_);
	return self;
}


GNodeGraph* gnode_graph_new (const gchar* title) {
	return gnode_graph_construct (GNODE_TYPE_GRAPH, title);
}


gboolean gnode_graph_is_connected (GNodeGraph* self) {
	gboolean result = FALSE;
	GNodeNode* first = NULL;
	GeeArrayList* _tmp0_ = NULL;
	gpointer _tmp1_ = NULL;
	GeeArrayList* traversed = NULL;
	GeeArrayList* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_nodes;
	_tmp1_ = gee_abstract_list_get ((GeeAbstractList*) _tmp0_, 0);
	first = (GNodeNode*) _tmp1_;
	_tmp2_ = gee_array_list_new (GNODE_TYPE_NODE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	traversed = _tmp2_;
	gee_abstract_collection_add ((GeeAbstractCollection*) traversed, first);
	_tmp3_ = gnode_graph_traverse_nodes (self, first, traversed);
	result = _tmp3_;
	_g_object_unref0 (traversed);
	_g_object_unref0 (first);
	return result;
}


void gnode_graph_add_node (GNodeGraph* self, GNodeNode* node) {
	GeeArrayList* _tmp0_ = NULL;
	GNodeNode* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (node != NULL);
	_tmp0_ = self->priv->_nodes;
	_tmp1_ = node;
	_tmp2_ = gee_abstract_collection_contains ((GeeAbstractCollection*) _tmp0_, _tmp1_);
	if (!_tmp2_) {
		GeeArrayList* _tmp3_ = NULL;
		GNodeNode* _tmp4_ = NULL;
		_tmp3_ = self->priv->_nodes;
		_tmp4_ = node;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp3_, _tmp4_);
	}
}


void gnode_graph_self_loop (GNodeGraph* self, GNodeNode* node, GNodeLink* edge) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (node != NULL);
	g_return_if_fail (edge != NULL);
}


static gboolean gnode_graph_traverse_nodes (GNodeGraph* self, GNodeNode* first, GeeArrayList* visited) {
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (first != NULL, FALSE);
	g_return_val_if_fail (visited != NULL, FALSE);
	result = FALSE;
	return result;
}


void gnode_graph_remove_link (GNodeGraph* self, GNodeLink* edge) {
	GeeArrayList* _tmp0_ = NULL;
	GNodeLink* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (edge != NULL);
	_tmp0_ = self->priv->_edges;
	_tmp1_ = edge;
	gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp0_, _tmp1_);
}


GeeArrayList* gnode_graph_shortest_path (GNodeGraph* self, GNodeNode* src, GNodeNode* dst) {
	GeeArrayList* result = NULL;
	GeeArrayList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (src != NULL, NULL);
	g_return_val_if_fail (dst != NULL, NULL);
	_tmp0_ = gee_array_list_new (GNODE_TYPE_LINK, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	result = _tmp0_;
	return result;
}


void gnode_graph_remove_edge (GNodeGraph* self, GNodeLink* edge) {
	GeeArrayList* _tmp0_ = NULL;
	GNodeLink* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (edge != NULL);
	_tmp0_ = self->priv->_edges;
	_tmp1_ = edge;
	gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp0_, _tmp1_);
}


void gnode_graph_add_edge (GNodeGraph* self, GNodeLink* edge) {
	GeeArrayList* _tmp0_ = NULL;
	GNodeLink* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (edge != NULL);
	_tmp0_ = self->priv->_edges;
	_tmp1_ = edge;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp1_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void gnode_graph_draw (GNodeGraph* self, cairo_t* ctx) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (ctx != NULL);
	{
		GeeArrayList* _edge_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _edge_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _edge_index = 0;
		_tmp0_ = self->priv->_edges;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_edge_list = _tmp1_;
		_tmp2_ = _edge_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_edge_size = _tmp4_;
		_edge_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			GNodeLink* edge = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			GNodeLink* _tmp11_ = NULL;
			cairo_t* _tmp12_ = NULL;
			_tmp5_ = _edge_index;
			_edge_index = _tmp5_ + 1;
			_tmp6_ = _edge_index;
			_tmp7_ = _edge_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _edge_list;
			_tmp9_ = _edge_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			edge = (GNodeLink*) _tmp10_;
			_tmp11_ = edge;
			_tmp12_ = ctx;
			gnode_link_draw (_tmp11_, _tmp12_);
			_g_object_unref0 (edge);
		}
		_g_object_unref0 (_edge_list);
	}
}


void gnode_graph_remove_node (GNodeGraph* self, GNodeNode* node) {
	GeeArrayList* _tmp20_ = NULL;
	GNodeNode* _tmp21_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (node != NULL);
	{
		GeeArrayList* _e_list = NULL;
		GNodeNode* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		GeeArrayList* _tmp2_ = NULL;
		GeeArrayList* _tmp3_ = NULL;
		gint _e_size = 0;
		GeeArrayList* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		gint _e_index = 0;
		_tmp0_ = node;
		_tmp1_ = gnode_node_get_edges (_tmp0_);
		_tmp2_ = _tmp1_;
		_tmp3_ = _g_object_ref0 (_tmp2_);
		_e_list = _tmp3_;
		_tmp4_ = _e_list;
		_tmp5_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp4_);
		_tmp6_ = _tmp5_;
		_e_size = _tmp6_;
		_e_index = -1;
		while (TRUE) {
			gint _tmp7_ = 0;
			gint _tmp8_ = 0;
			gint _tmp9_ = 0;
			GNodeLink* e = NULL;
			GeeArrayList* _tmp10_ = NULL;
			gint _tmp11_ = 0;
			gpointer _tmp12_ = NULL;
			GNodeLink* _tmp13_ = NULL;
			GNodeNode* _tmp14_ = NULL;
			GNodeNode* _tmp15_ = NULL;
			GNodeNode* _tmp16_ = NULL;
			GNodeLink* _tmp17_ = NULL;
			GNodeNode* _tmp18_ = NULL;
			GNodeLink* _tmp19_ = NULL;
			_tmp7_ = _e_index;
			_e_index = _tmp7_ + 1;
			_tmp8_ = _e_index;
			_tmp9_ = _e_size;
			if (!(_tmp8_ < _tmp9_)) {
				break;
			}
			_tmp10_ = _e_list;
			_tmp11_ = _e_index;
			_tmp12_ = gee_abstract_list_get ((GeeAbstractList*) _tmp10_, _tmp11_);
			e = (GNodeLink*) _tmp12_;
			_tmp13_ = e;
			_tmp14_ = node;
			_tmp15_ = gnode_link_get_pair (_tmp13_, _tmp14_);
			_tmp16_ = _tmp15_;
			_tmp17_ = e;
			gnode_node_unlink (_tmp16_, _tmp17_);
			_g_object_unref0 (_tmp16_);
			_tmp18_ = node;
			_tmp19_ = e;
			gnode_node_unlink (_tmp18_, _tmp19_);
			_g_object_unref0 (e);
		}
		_g_object_unref0 (_e_list);
	}
	_tmp20_ = self->priv->_nodes;
	_tmp21_ = node;
	gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp20_, _tmp21_);
}


const gchar* gnode_graph_get_title (GNodeGraph* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_title;
	result = _tmp0_;
	return result;
}


static void gnode_graph_set_title (GNodeGraph* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_title);
	self->priv->_title = _tmp1_;
	g_object_notify ((GObject *) self, "title");
}


static GeeArrayList* gnode_graph_get_nodes (GNodeGraph* self) {
	GeeArrayList* result;
	GeeArrayList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_nodes;
	result = _tmp0_;
	return result;
}


static void gnode_graph_set_nodes (GNodeGraph* self, GeeArrayList* value) {
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_nodes);
	self->priv->_nodes = _tmp1_;
}


static GeeArrayList* gnode_graph_get_edges (GNodeGraph* self) {
	GeeArrayList* result;
	GeeArrayList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_edges;
	result = _tmp0_;
	return result;
}


static void gnode_graph_set_edges (GNodeGraph* self, GeeArrayList* value) {
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_edges);
	self->priv->_edges = _tmp1_;
}


static void gnode_graph_class_init (GNodeGraphClass * klass) {
	gnode_graph_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GNodeGraphPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_gnode_graph_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_gnode_graph_set_property;
	G_OBJECT_CLASS (klass)->finalize = gnode_graph_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNODE_GRAPH_TITLE, g_param_spec_string ("title", "title", "title", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void gnode_graph_instance_init (GNodeGraph * self) {
	self->priv = GNODE_GRAPH_GET_PRIVATE (self);
}


static void gnode_graph_finalize (GObject* obj) {
	GNodeGraph * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GNODE_TYPE_GRAPH, GNodeGraph);
	_g_free0 (self->priv->_title);
	_g_object_unref0 (self->priv->_nodes);
	_g_object_unref0 (self->priv->_edges);
	G_OBJECT_CLASS (gnode_graph_parent_class)->finalize (obj);
}


GType gnode_graph_get_type (void) {
	static volatile gsize gnode_graph_type_id__volatile = 0;
	if (g_once_init_enter (&gnode_graph_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GNodeGraphClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gnode_graph_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GNodeGraph), 0, (GInstanceInitFunc) gnode_graph_instance_init, NULL };
		GType gnode_graph_type_id;
		gnode_graph_type_id = g_type_register_static (G_TYPE_OBJECT, "GNodeGraph", &g_define_type_info, 0);
		g_once_init_leave (&gnode_graph_type_id__volatile, gnode_graph_type_id);
	}
	return gnode_graph_type_id__volatile;
}


static void _vala_gnode_graph_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GNodeGraph * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GNODE_TYPE_GRAPH, GNodeGraph);
	switch (property_id) {
		case GNODE_GRAPH_TITLE:
		g_value_set_string (value, gnode_graph_get_title (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_gnode_graph_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GNodeGraph * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GNODE_TYPE_GRAPH, GNodeGraph);
	switch (property_id) {
		case GNODE_GRAPH_TITLE:
		gnode_graph_set_title (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



