/* main.c generated by valac 0.24.0, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>


#define GNODE_TYPE_APP (gnode_app_get_type ())
#define GNODE_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNODE_TYPE_APP, GNodeApp))
#define GNODE_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNODE_TYPE_APP, GNodeAppClass))
#define GNODE_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNODE_TYPE_APP))
#define GNODE_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNODE_TYPE_APP))
#define GNODE_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNODE_TYPE_APP, GNodeAppClass))

typedef struct _GNodeApp GNodeApp;
typedef struct _GNodeAppClass GNodeAppClass;
typedef struct _GNodeAppPrivate GNodeAppPrivate;

#define GNODE_TYPE_WINDOW (gnode_window_get_type ())
#define GNODE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNODE_TYPE_WINDOW, GNodeWindow))
#define GNODE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNODE_TYPE_WINDOW, GNodeWindowClass))
#define GNODE_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNODE_TYPE_WINDOW))
#define GNODE_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNODE_TYPE_WINDOW))
#define GNODE_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNODE_TYPE_WINDOW, GNodeWindowClass))

typedef struct _GNodeWindow GNodeWindow;
typedef struct _GNodeWindowClass GNodeWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GNodeApp {
	GtkApplication parent_instance;
	GNodeAppPrivate * priv;
};

struct _GNodeAppClass {
	GtkApplicationClass parent_class;
};


static gpointer gnode_app_parent_class = NULL;

GType gnode_app_get_type (void) G_GNUC_CONST;
enum  {
	GNODE_APP_DUMMY_PROPERTY
};
GNodeApp* gnode_app_new (void);
GNodeApp* gnode_app_construct (GType object_type);
static void gnode_app_real_activate (GApplication* base);
GType gnode_window_get_type (void) G_GNUC_CONST;
GNodeWindow* gnode_window_new (GNodeApp* parent);
GNodeWindow* gnode_window_construct (GType object_type, GNodeApp* parent);
gint gnode_app_main (gchar** args, int args_length1);


GNodeApp* gnode_app_construct (GType object_type) {
	GNodeApp * self = NULL;
	self = (GNodeApp*) g_object_new (object_type, "application-id", "com.nongnu.gnode", "flags", G_APPLICATION_FLAGS_NONE, NULL);
	return self;
}


GNodeApp* gnode_app_new (void) {
	return gnode_app_construct (GNODE_TYPE_APP);
}


static void gnode_app_real_activate (GApplication* base) {
	GNodeApp * self;
	GNodeWindow* window = NULL;
	GNodeWindow* _tmp0_ = NULL;
	self = (GNodeApp*) base;
	_tmp0_ = gnode_window_new (self);
	g_object_ref_sink (_tmp0_);
	window = _tmp0_;
	gtk_widget_show_all ((GtkWidget*) window);
	_g_object_unref0 (window);
}


gint gnode_app_main (gchar** args, int args_length1) {
	gint result = 0;
	GNodeApp* app = NULL;
	GNodeApp* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
	_tmp0_ = gnode_app_new ();
	app = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
	result = _tmp2_;
	_g_object_unref0 (app);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return gnode_app_main (argv, argc);
}


static void gnode_app_class_init (GNodeAppClass * klass) {
	gnode_app_parent_class = g_type_class_peek_parent (klass);
	G_APPLICATION_CLASS (klass)->activate = gnode_app_real_activate;
}


static void gnode_app_instance_init (GNodeApp * self) {
}


GType gnode_app_get_type (void) {
	static volatile gsize gnode_app_type_id__volatile = 0;
	if (g_once_init_enter (&gnode_app_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GNodeAppClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gnode_app_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GNodeApp), 0, (GInstanceInitFunc) gnode_app_instance_init, NULL };
		GType gnode_app_type_id;
		gnode_app_type_id = g_type_register_static (GTK_TYPE_APPLICATION, "GNodeApp", &g_define_type_info, 0);
		g_once_init_leave (&gnode_app_type_id__volatile, gnode_app_type_id);
	}
	return gnode_app_type_id__volatile;
}



