/* node.c generated by valac 0.24.0, the Vala compiler
 * generated from node.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gee.h>
#include <cairo.h>
#include <gdk/gdk.h>


#define GNODE_TYPE_NODE (gnode_node_get_type ())
#define GNODE_NODE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNODE_TYPE_NODE, GNodeNode))
#define GNODE_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNODE_TYPE_NODE, GNodeNodeClass))
#define GNODE_IS_NODE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNODE_TYPE_NODE))
#define GNODE_IS_NODE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNODE_TYPE_NODE))
#define GNODE_NODE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNODE_TYPE_NODE, GNodeNodeClass))

typedef struct _GNodeNode GNodeNode;
typedef struct _GNodeNodeClass GNodeNodeClass;
typedef struct _GNodeNodePrivate GNodeNodePrivate;

#define GNODE_TYPE_GRAPH (gnode_graph_get_type ())
#define GNODE_GRAPH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNODE_TYPE_GRAPH, GNodeGraph))
#define GNODE_GRAPH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNODE_TYPE_GRAPH, GNodeGraphClass))
#define GNODE_IS_GRAPH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNODE_TYPE_GRAPH))
#define GNODE_IS_GRAPH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNODE_TYPE_GRAPH))
#define GNODE_GRAPH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNODE_TYPE_GRAPH, GNodeGraphClass))

typedef struct _GNodeGraph GNodeGraph;
typedef struct _GNodeGraphClass GNodeGraphClass;

#define GNODE_TYPE_LINK (gnode_link_get_type ())
#define GNODE_LINK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GNODE_TYPE_LINK, GNodeLink))
#define GNODE_LINK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GNODE_TYPE_LINK, GNodeLinkClass))
#define GNODE_IS_LINK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GNODE_TYPE_LINK))
#define GNODE_IS_LINK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GNODE_TYPE_LINK))
#define GNODE_LINK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GNODE_TYPE_LINK, GNodeLinkClass))

typedef struct _GNodeLink GNodeLink;
typedef struct _GNodeLinkClass GNodeLinkClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GNodeNode {
	GObject parent_instance;
	GNodeNodePrivate * priv;
};

struct _GNodeNodeClass {
	GObjectClass parent_class;
};

struct _GNodeNodePrivate {
	gchar* _label;
	GNodeGraph* graph;
	gdouble _x;
	gdouble _y;
	guint radius;
	GeeArrayList* _edges;
};


static gpointer gnode_node_parent_class = NULL;

GType gnode_node_get_type (void) G_GNUC_CONST;
GType gnode_graph_get_type (void) G_GNUC_CONST;
GType gnode_link_get_type (void) G_GNUC_CONST;
#define GNODE_NODE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GNODE_TYPE_NODE, GNodeNodePrivate))
enum  {
	GNODE_NODE_DUMMY_PROPERTY,
	GNODE_NODE_LABEL,
	GNODE_NODE_X,
	GNODE_NODE_Y,
	GNODE_NODE_EDGES,
	GNODE_NODE_DEGREE
};
GNodeNode* gnode_node_new (const gchar* label, GNodeGraph* parent, gdouble x, gdouble y);
GNodeNode* gnode_node_construct (GType object_type, const gchar* label, GNodeGraph* parent, gdouble x, gdouble y);
static void gnode_node_set_label (GNodeNode* self, const gchar* value);
static void gnode_node_set_edges (GNodeNode* self, GeeArrayList* value);
static void gnode_node_set_x (GNodeNode* self, gdouble value);
static void gnode_node_set_y (GNodeNode* self, gdouble value);
void gnode_node_connect_from (GNodeNode* self, GNodeNode* source, GNodeLink* edge);
GeeArrayList* gnode_node_get_edges (GNodeNode* self);
void gnode_graph_self_loop (GNodeGraph* self, GNodeNode* node, GNodeLink* edge);
void gnode_node_connect_to (GNodeNode* self, GNodeNode* dest, gdouble weigth);
GNodeLink* gnode_link_new (GNodeNode* src, GNodeNode* dst, gdouble weight, GNodeGraph* parent);
GNodeLink* gnode_link_construct (GType object_type, GNodeNode* src, GNodeNode* dst, gdouble weight, GNodeGraph* parent);
void gnode_graph_add_edge (GNodeGraph* self, GNodeLink* edge);
void gnode_node_siege (GNodeNode* self, GNodeNode* next);
GNodeNode* gnode_link_get_pair (GNodeLink* self, GNodeNode* node);
void gnode_node_unlink (GNodeNode* self, GNodeLink* edge);
void gnode_node_draw (GNodeNode* self, cairo_t* ctx);
gdouble gnode_node_get_x (GNodeNode* self);
gdouble gnode_node_get_y (GNodeNode* self);
gboolean gnode_node_clicked (GNodeNode* self, GdkPoint* click);
void gnode_link_unlink (GNodeLink* self, GNodeNode* node);
const gchar* gnode_node_get_label (GNodeNode* self);
guint gnode_node_get_degree (GNodeNode* self);
static void gnode_node_finalize (GObject* obj);
static void _vala_gnode_node_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gnode_node_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


GNodeNode* gnode_node_construct (GType object_type, const gchar* label, GNodeGraph* parent, gdouble x, gdouble y) {
	GNodeNode * self = NULL;
	const gchar* _tmp0_ = NULL;
	GNodeGraph* _tmp1_ = NULL;
	GNodeGraph* _tmp2_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
	gdouble _tmp4_ = 0.0;
	gdouble _tmp5_ = 0.0;
	g_return_val_if_fail (label != NULL, NULL);
	g_return_val_if_fail (parent != NULL, NULL);
	self = (GNodeNode*) g_object_new (object_type, NULL);
	_tmp0_ = label;
	gnode_node_set_label (self, _tmp0_);
	_tmp1_ = parent;
	_tmp2_ = _g_object_ref0 (_tmp1_);
	_g_object_unref0 (self->priv->graph);
	self->priv->graph = _tmp2_;
	_tmp3_ = gee_array_list_new (GNODE_TYPE_LINK, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	gnode_node_set_edges (self, _tmp3_);
	_tmp4_ = x;
	gnode_node_set_x (self, _tmp4_);
	_tmp5_ = y;
	gnode_node_set_y (self, _tmp5_);
	return self;
}


GNodeNode* gnode_node_new (const gchar* label, GNodeGraph* parent, gdouble x, gdouble y) {
	return gnode_node_construct (GNODE_TYPE_NODE, label, parent, x, y);
}


void gnode_node_connect_from (GNodeNode* self, GNodeNode* source, GNodeLink* edge) {
	GeeArrayList* _tmp0_ = NULL;
	GNodeLink* _tmp1_ = NULL;
	GNodeNode* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (source != NULL);
	g_return_if_fail (edge != NULL);
	_tmp0_ = self->priv->_edges;
	_tmp1_ = edge;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp0_, _tmp1_);
	_tmp2_ = source;
	if (_tmp2_ == self) {
		GNodeGraph* _tmp3_ = NULL;
		GNodeLink* _tmp4_ = NULL;
		_tmp3_ = self->priv->graph;
		_tmp4_ = edge;
		gnode_graph_self_loop (_tmp3_, self, _tmp4_);
	}
}


void gnode_node_connect_to (GNodeNode* self, GNodeNode* dest, gdouble weigth) {
	GNodeLink* edge = NULL;
	GNodeNode* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	GNodeGraph* _tmp2_ = NULL;
	GNodeLink* _tmp3_ = NULL;
	GeeArrayList* _tmp4_ = NULL;
	GNodeGraph* _tmp5_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (dest != NULL);
	_tmp0_ = dest;
	_tmp1_ = weigth;
	_tmp2_ = self->priv->graph;
	_tmp3_ = gnode_link_new (self, _tmp0_, _tmp1_, _tmp2_);
	edge = _tmp3_;
	_tmp4_ = self->priv->_edges;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp4_, edge);
	_tmp5_ = self->priv->graph;
	gnode_graph_add_edge (_tmp5_, edge);
	_g_object_unref0 (edge);
}


void gnode_node_siege (GNodeNode* self, GNodeNode* next) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (next != NULL);
	{
		GeeArrayList* _edge_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _edge_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _edge_index = 0;
		_tmp0_ = self->priv->_edges;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_edge_list = _tmp1_;
		_tmp2_ = _edge_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_edge_size = _tmp4_;
		_edge_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			GNodeLink* edge = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			GNodeLink* _tmp11_ = NULL;
			GNodeNode* _tmp12_ = NULL;
			GNodeNode* _tmp13_ = NULL;
			GNodeNode* _tmp14_ = NULL;
			gboolean _tmp15_ = FALSE;
			_tmp5_ = _edge_index;
			_edge_index = _tmp5_ + 1;
			_tmp6_ = _edge_index;
			_tmp7_ = _edge_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _edge_list;
			_tmp9_ = _edge_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			edge = (GNodeLink*) _tmp10_;
			_tmp11_ = edge;
			_tmp12_ = gnode_link_get_pair (_tmp11_, self);
			_tmp13_ = _tmp12_;
			_tmp14_ = next;
			_tmp15_ = _tmp13_ == _tmp14_;
			_g_object_unref0 (_tmp13_);
			if (_tmp15_) {
				GNodeLink* _tmp16_ = NULL;
				GNodeNode* _tmp17_ = NULL;
				GNodeLink* _tmp18_ = NULL;
				_tmp16_ = edge;
				gnode_node_unlink (self, _tmp16_);
				_tmp17_ = next;
				_tmp18_ = edge;
				gnode_node_unlink (_tmp17_, _tmp18_);
			}
			_g_object_unref0 (edge);
		}
		_g_object_unref0 (_edge_list);
	}
}


void gnode_node_draw (GNodeNode* self, cairo_t* ctx) {
	cairo_t* _tmp0_ = NULL;
	cairo_t* _tmp1_ = NULL;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (ctx != NULL);
	_tmp0_ = ctx;
	cairo_set_line_width (_tmp0_, 6.0);
	_tmp1_ = ctx;
	_tmp2_ = self->priv->_x;
	_tmp3_ = self->priv->_y;
	cairo_arc (_tmp1_, _tmp2_, _tmp3_, 10.0, (gdouble) 0, 2 * G_PI);
}


gboolean gnode_node_clicked (GNodeNode* self, GdkPoint* click) {
	gboolean result = FALSE;
	gdouble dist = 0.0;
	GdkPoint _tmp0_ = {0};
	gint _tmp1_ = 0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	GdkPoint _tmp4_ = {0};
	gint _tmp5_ = 0;
	gdouble _tmp6_ = 0.0;
	gdouble _tmp7_ = 0.0;
	gdouble _tmp8_ = 0.0;
	guint _tmp9_ = 0U;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (click != NULL, FALSE);
	_tmp0_ = *click;
	_tmp1_ = _tmp0_.x;
	_tmp2_ = self->priv->_x;
	_tmp3_ = pow (_tmp1_ - _tmp2_, (gdouble) 2);
	_tmp4_ = *click;
	_tmp5_ = _tmp4_.y;
	_tmp6_ = self->priv->_y;
	_tmp7_ = pow (_tmp5_ - _tmp6_, (gdouble) 2);
	_tmp8_ = sqrt (_tmp3_ + _tmp7_);
	dist = _tmp8_;
	_tmp9_ = self->priv->radius;
	result = dist < ((gdouble) _tmp9_);
	return result;
}


void gnode_node_unlink (GNodeNode* self, GNodeLink* edge) {
	GNodeLink* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	GNodeLink* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (edge != NULL);
	_tmp0_ = edge;
	gnode_link_unlink (_tmp0_, self);
	_tmp1_ = self->priv->_edges;
	_tmp2_ = edge;
	gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp1_, _tmp2_);
}


const gchar* gnode_node_get_label (GNodeNode* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_label;
	result = _tmp0_;
	return result;
}


static void gnode_node_set_label (GNodeNode* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_label);
	self->priv->_label = _tmp1_;
	g_object_notify ((GObject *) self, "label");
}


gdouble gnode_node_get_x (GNodeNode* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_x;
	result = _tmp0_;
	return result;
}


static void gnode_node_set_x (GNodeNode* self, gdouble value) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_x = _tmp0_;
	g_object_notify ((GObject *) self, "x");
}


gdouble gnode_node_get_y (GNodeNode* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_y;
	result = _tmp0_;
	return result;
}


static void gnode_node_set_y (GNodeNode* self, gdouble value) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_y = _tmp0_;
	g_object_notify ((GObject *) self, "y");
}


GeeArrayList* gnode_node_get_edges (GNodeNode* self) {
	GeeArrayList* result;
	GeeArrayList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_edges;
	result = _tmp0_;
	return result;
}


static void gnode_node_set_edges (GNodeNode* self, GeeArrayList* value) {
	GeeArrayList* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	value = NULL;
	_g_object_unref0 (self->priv->_edges);
	self->priv->_edges = _tmp0_;
	_g_object_unref0 (value);
	g_object_notify ((GObject *) self, "edges");
}


guint gnode_node_get_degree (GNodeNode* self) {
	guint result;
	GeeArrayList* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, 0U);
	_tmp0_ = self->priv->_edges;
	_tmp1_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp0_);
	_tmp2_ = _tmp1_;
	result = (guint) _tmp2_;
	return result;
}


static void gnode_node_class_init (GNodeNodeClass * klass) {
	gnode_node_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GNodeNodePrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_gnode_node_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_gnode_node_set_property;
	G_OBJECT_CLASS (klass)->finalize = gnode_node_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNODE_NODE_LABEL, g_param_spec_string ("label", "label", "label", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNODE_NODE_X, g_param_spec_double ("x", "x", "x", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNODE_NODE_Y, g_param_spec_double ("y", "y", "y", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNODE_NODE_EDGES, g_param_spec_object ("edges", "edges", "edges", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GNODE_NODE_DEGREE, g_param_spec_uint ("degree", "degree", "degree", 0, G_MAXUINT, 0U, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void gnode_node_instance_init (GNodeNode * self) {
	self->priv = GNODE_NODE_GET_PRIVATE (self);
	self->priv->radius = (guint) 1;
}


static void gnode_node_finalize (GObject* obj) {
	GNodeNode * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GNODE_TYPE_NODE, GNodeNode);
	_g_free0 (self->priv->_label);
	_g_object_unref0 (self->priv->graph);
	_g_object_unref0 (self->priv->_edges);
	G_OBJECT_CLASS (gnode_node_parent_class)->finalize (obj);
}


GType gnode_node_get_type (void) {
	static volatile gsize gnode_node_type_id__volatile = 0;
	if (g_once_init_enter (&gnode_node_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GNodeNodeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gnode_node_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GNodeNode), 0, (GInstanceInitFunc) gnode_node_instance_init, NULL };
		GType gnode_node_type_id;
		gnode_node_type_id = g_type_register_static (G_TYPE_OBJECT, "GNodeNode", &g_define_type_info, 0);
		g_once_init_leave (&gnode_node_type_id__volatile, gnode_node_type_id);
	}
	return gnode_node_type_id__volatile;
}


static void _vala_gnode_node_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GNodeNode * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GNODE_TYPE_NODE, GNodeNode);
	switch (property_id) {
		case GNODE_NODE_LABEL:
		g_value_set_string (value, gnode_node_get_label (self));
		break;
		case GNODE_NODE_X:
		g_value_set_double (value, gnode_node_get_x (self));
		break;
		case GNODE_NODE_Y:
		g_value_set_double (value, gnode_node_get_y (self));
		break;
		case GNODE_NODE_EDGES:
		g_value_set_object (value, gnode_node_get_edges (self));
		break;
		case GNODE_NODE_DEGREE:
		g_value_set_uint (value, gnode_node_get_degree (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_gnode_node_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GNodeNode * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GNODE_TYPE_NODE, GNodeNode);
	switch (property_id) {
		case GNODE_NODE_LABEL:
		gnode_node_set_label (self, g_value_get_string (value));
		break;
		case GNODE_NODE_X:
		gnode_node_set_x (self, g_value_get_double (value));
		break;
		case GNODE_NODE_Y:
		gnode_node_set_y (self, g_value_get_double (value));
		break;
		case GNODE_NODE_EDGES:
		gnode_node_set_edges (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



